# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Xcode@5
  inputs:
    actions: 'build'
    xcodeVersion: '10'
    packageApp: false
    sdk: ios14
    testRunTitle: run build test 
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
workspace:
  xxx
  clean: 
  parameters:
    - 